In [29]:
import numpy as np
import matplotlib.pyplot as plt
import random

🌟 Exercise 1 : Array Creation and Manipulation

Instructions

Create a 1D NumPy array containing numbers from 0 to 9.

In [30]:
np_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
print("Original array:", np_array)

Original array: [0 1 2 3 4 5 6 7 8 9]


🌟 Exercise 2 : Type Conversion and Array Operations

Instructions

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [32]:
my_list = [3.14, 2.17, 0, 1, 2]
my_array = np.array(my_list, dtype=int)
print("Converted array:", my_array)

Converted array: [3 2 0 1 2]


🌟 Exercise 3 : Working with Multi-Dimensional Arrays

Instructions

Create a 3x3 NumPy array with values ranging from 1 to 9.

In [48]:
array_3d = np.arange(1,10).reshape(3, 3)

In [49]:
print("Multi-dimension array:", array_3d)

Multi-dimension array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

Instructions

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [35]:
random_array = np.random.rand(4,5)
print("Random 4,5 array:", random_array)

Random 4,5 array: [[0.52466021 0.31753789 0.11122191 0.76099663 0.75135429]
 [0.21414244 0.08515222 0.33138359 0.25755451 0.24185224]
 [0.45051158 0.34005597 0.18716586 0.61594234 0.88780657]
 [0.15301876 0.85135773 0.19347189 0.21214003 0.19353812]]


🌟 Exercise 5 : Indexing Arrays

Instructions

Select the second row from a given 2D NumPy array.

In [36]:
array_2d = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

Second row: [20 21 22 23 24]


🌟 Exercise 6 : Reversing elements

Instructions

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [37]:
arr = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
reversed_arr = arr[::-1]
print(reversed_arr) 

[0 1 2 3 4 5 6 7 8 9]


🌟 Exercise 7 : Identity Matrix

Instructions

Create a 4x4 identity matrix using NumPy.

In [38]:
identity_matrix_2 = np.identity(4)
print(identity_matrix_2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


🌟 Exercise 8 : Simple Aggregate Funcs

Instructions

Find the sum and average of a given 1D array.

In [39]:
np_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print("Sum:",np.sum(np_array),",","Average:",np.mean(np_array))

Sum: 136 , Average: 8.0


🌟 Exercise 9 : Create Array and Change its Structure

Instructions

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [42]:
array_1_20 = np.arange(1, 21)
reshaped_array = array_1_20.reshape(4,5)
print("Reshaped to 4x5:\n", reshaped_array)

Reshaped to 4x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


🌟 Exercise 10 : Conditional Selection of Values

Instructions

Extract all odd numbers from a given NumPy array.

In [45]:
arr = np.arange(10)
odd_numbers = arr[arr % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]
