In [1]:
import numpy as np

# Creating a matrix
matrix_A = np.array([[1, 2], [3, 4]])
print("Matrix A:\n", matrix_A)

# Reshaping a matrix
reshaped_matrix = np.reshape(matrix_A, (4, 1))
print("Reshaped Matrix:\n", reshaped_matrix)

# Changing values in a matrix
matrix_A[0, 0] = 5
print("Updated Matrix A:\n", matrix_A)

Matrix A:
 [[1 2]
 [3 4]]
Reshaped Matrix:
 [[1]
 [2]
 [3]
 [4]]
Updated Matrix A:
 [[5 2]
 [3 4]]


In [2]:
# Example survey data matrix (5 respondents, 4 questions)
survey_data = np.array([[5, 1, 4, 4],
                        [4, 2, 4, 3],
                        [5, 1, 1, 5],
                        [3, 2, 1, 2],
                        [2, 1, 2, 5]])

# Calculating various statistics
average_responses = np.mean(survey_data, axis=0)
total_responses = np.sum(survey_data, axis=0)
max_responses = np.max(survey_data, axis=0)
min_responses = np.min(survey_data, axis=0)

print("Average Responses:", average_responses)
print("Total Responses:", total_responses)
print("Maximum Responses:", max_responses)
print("Minimum Responses:", min_responses)

Average Responses: [3.8 1.4 2.4 3.8]
Total Responses: [19  7 12 19]
Maximum Responses: [5 2 4 5]
Minimum Responses: [2 1 1 2]


In [3]:
# Random sampling from an array
data = np.arange(10)
sample = np.random.choice(data, size=5, replace=False)
print("Random Sample:", sample)

Random Sample: [2 3 6 5 4]


In [4]:
# Shuffling data
np.random.shuffle(data)
print("Shuffled Data:", data)

Shuffled Data: [0 5 1 4 3 2 7 9 6 8]


In [5]:
# Creating date ranges
dates = np.arange('2020-01', '2020-02', dtype='datetime64[D]')
print("January 2020 Dates:\n", dates)

January 2020 Dates:
 ['2020-01-01' '2020-01-02' '2020-01-03' '2020-01-04' '2020-01-05'
 '2020-01-06' '2020-01-07' '2020-01-08' '2020-01-09' '2020-01-10'
 '2020-01-11' '2020-01-12' '2020-01-13' '2020-01-14' '2020-01-15'
 '2020-01-16' '2020-01-17' '2020-01-18' '2020-01-19' '2020-01-20'
 '2020-01-21' '2020-01-22' '2020-01-23' '2020-01-24' '2020-01-25'
 '2020-01-26' '2020-01-27' '2020-01-28' '2020-01-29' '2020-01-30'
 '2020-01-31']


In [6]:
# Converting dates to a different format
formatted_dates = np.datetime_as_string(dates, unit='D')
print("Formatted Dates:\n", formatted_dates)

Formatted Dates:
 ['2020-01-01' '2020-01-02' '2020-01-03' '2020-01-04' '2020-01-05'
 '2020-01-06' '2020-01-07' '2020-01-08' '2020-01-09' '2020-01-10'
 '2020-01-11' '2020-01-12' '2020-01-13' '2020-01-14' '2020-01-15'
 '2020-01-16' '2020-01-17' '2020-01-18' '2020-01-19' '2020-01-20'
 '2020-01-21' '2020-01-22' '2020-01-23' '2020-01-24' '2020-01-25'
 '2020-01-26' '2020-01-27' '2020-01-28' '2020-01-29' '2020-01-30'
 '2020-01-31']


In [10]:
import pandas as pd

# Example: Using rolling statistics
ts_data = pd.Series(np.random.randn(100), index=pd.date_range('today', periods=100))
rolling_mean = ts_data.rolling(window=5, min_periods=1).mean()
print("Rolling Mean:\n", rolling_mean)

# Example: Applying a window function
window_sum = ts_data.rolling(window=5, min_periods=1).sum()
print("Window Sum:\n", window_sum)

Rolling Mean:
 2026-07-27 14:20:05.264444   -0.524532
2026-07-28 14:20:05.264444    0.393808
2026-07-29 14:20:05.264444    0.574482
2026-07-30 14:20:05.264444    0.248800
2026-07-31 14:20:05.264444    0.476658
                                ...   
2026-10-30 14:20:05.264444   -0.566961
2026-10-31 14:20:05.264444   -0.401067
2026-11-01 14:20:05.264444    0.073026
2026-11-02 14:20:05.264444   -0.087571
2026-11-03 14:20:05.264444   -0.051411
Freq: D, Length: 100, dtype: float64
Window Sum:
 2026-07-27 14:20:05.264444   -0.524532
2026-07-28 14:20:05.264444    0.787616
2026-07-29 14:20:05.264444    1.723447
2026-07-30 14:20:05.264444    0.995202
2026-07-31 14:20:05.264444    2.383291
                                ...   
2026-10-30 14:20:05.264444   -2.834804
2026-10-31 14:20:05.264444   -2.005337
2026-11-01 14:20:05.264444    0.365130
2026-11-02 14:20:05.264444   -0.437857
2026-11-03 14:20:05.264444   -0.257055
Freq: D, Length: 100, dtype: float64


In [11]:
# Applying a window function
window_sum = ts_data.rolling(window=5, min_periods=1).sum()
print("Window Sum:\n", window_sum)

Window Sum:
 2026-07-27 14:20:05.264444   -0.524532
2026-07-28 14:20:05.264444    0.787616
2026-07-29 14:20:05.264444    1.723447
2026-07-30 14:20:05.264444    0.995202
2026-07-31 14:20:05.264444    2.383291
                                ...   
2026-10-30 14:20:05.264444   -2.834804
2026-10-31 14:20:05.264444   -2.005337
2026-11-01 14:20:05.264444    0.365130
2026-11-02 14:20:05.264444   -0.437857
2026-11-03 14:20:05.264444   -0.257055
Freq: D, Length: 100, dtype: float64


In [12]:
# Create a large array
large_array = np.arange(1000000)

# Inspect memory layout
print("Array size:", large_array.size)
print("Item size:", large_array.itemsize)
print("Memory usage (bytes):", large_array.size * large_array.itemsize)

Array size: 1000000
Item size: 8
Memory usage (bytes): 8000000


In [13]:
# Check memory contiguity
print("C-contiguous:", large_array.flags['C_CONTIGUOUS'])
print("F-contiguous:", large_array.flags['F_CONTIGUOUS'])

C-contiguous: True
F-contiguous: True


In [14]:
# Vectorized addition
result = large_array + large_array

In [16]:
# Broadcasting a smaller array
small_array = np.array([1, 2, 3])
broadcasted_result = large_array[:3] + small_array
print("Broadcasted Result:", broadcasted_result)

Broadcasted Result: [1 3 5]
